# Generated by Django 4.2.4 on 2023-08-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='飛行日')),
                ('pilot', models.CharField(max_length=100, verbose_name='操縦者')),
                ('takeoff_time', models.DateTimeField(auto_now_add=True, verbose_name='着陸時間')),
                ('landing_time', models.DateField(auto_now=True, verbose_name='離陸時間')),
                ('takeoff_location', models.CharField(max_length=255, verbose_name='着陸地点')),
                ('landing_location', models.CharField(max_length=255, verbose_name='離陸地点')),
            ],
        ),
    ]
