# Generated by Django 4.2.4 on 2023-08-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drone_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="飛行日")),
                ("pilot", models.CharField(max_length=100, verbose_name="操縦者")),
                ("takeoff_time", models.DateTimeField(verbose_name="離陸時間")),
                ("landing_time", models.DateTimeField(verbose_name="着陸時間")),
                (
                    "takeoff_location",
                    models.CharField(max_length=255, verbose_name="離陸地点"),
                ),
                (
                    "landing_location",
                    models.CharField(max_length=255, verbose_name="着陸地点"),
                ),
                ("takeoff_location_lat", models.FloatField(blank=True, null=True)),
                ("takeoff_location_lng", models.FloatField(blank=True, null=True)),
                ("landing_location_lat", models.FloatField(blank=True, null=True)),
                ("landing_location_lng", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="flight",
            name="landing_location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="landing_location_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="takeoff_location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="takeoff_location_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flight",
            name="landing_location",
            field=models.CharField(max_length=255, verbose_name="着陸地点"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="landing_time",
            field=models.DateTimeField(verbose_name="着陸時間"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="takeoff_location",
            field=models.CharField(max_length=255, verbose_name="離陸地点"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="takeoff_time",
            field=models.DateTimeField(verbose_name="離陸時間"),
        ),
    ]
