# Generated by Django 4.2.4 on 2023-09-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0004_flightrecord_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrecord',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
