# Generated by Django 4.2.4 on 2023-09-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0006_flight_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='飛行概要'),
        ),
        migrations.AlterField(
            model_name='flightrecord',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='飛行概要'),
        ),
    ]
