# Generated by Django 4.2.4 on 2023-09-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0009_maintenancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='inspection_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='inspector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
